apiVersion: apps/v1
kind: Deployment
metadata:
  name: version-backend-deployment
  labels:
    app: version-backend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: undefined
          image: coderpews/version-app:1.0