apiVersion: v1
kind: Service
metadata:
  name: workshop
  annotations:
    external-dns.alpha.kubernetes.io/hostname: workshop.aws5.tv2.no
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 80
  selector:
    app: workshop

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: workshop
spec:
  template:
    metadata:
      labels:
        app: workshop
    spec:
      containers:
        - image: coderpews/k8s-workshop:1.1
          name: workshop
          ports:
            - containerPort: 80
              name: http