apiVersion: v1
kind: Service
metadata:
  name: workshop
  annotations:
    external-dns.alpha.kubernetes.io/hostname: workshop.aws5.tv2.no
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: 80
  selector:
    app: workshop

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: workshop
spec:
  template:
    metadata:
      labels:
        app: workshop
    spec:
      containers:
        - image: coderpews/k8s-workshop:1.3
          name: workshop
          ports:
            - containerPort: 80
              name: http

---

  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
    name: version-backend-ingress
  spec:
    rules:
      - host: wrk.aws5.tv2.no
        http:
          paths:
            - path: /
              backend:
                serviceName: workshop
                servicePort: 80
       